version: "3"

services:
  mercadolivre-exemplo:
    image: php:8.1-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    networks:
      - mynetwork
    environment:
      - teste=1

networks:
  mynetwork:
    external: true
